BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(24);
CREATE TEMP TABLE device_test_ids AS SELECT gen_random_uuid() AS u1, gen_random_uuid() AS u2, gen_random_uuid() AS device;
GRANT SELECT ON device_test_ids TO authenticated, anon, service_role;
INSERT INTO auth.users(id) SELECT u1 FROM device_test_ids UNION ALL SELECT u2 FROM device_test_ids;
SELECT set_config('request.jwt.claim.sub', (SELECT u1::text FROM device_test_ids), true);
SET LOCAL ROLE authenticated;
SELECT lives_ok($$SELECT public.record_user_device(device, 'Safari', '18.0', 'iOS', 'phone') FROM device_test_ids$$, 'authenticated observation succeeds');
SELECT is((SELECT count(*) FROM public.user_devices), 1::bigint, 'one browser recorded');
SELECT is((SELECT user_id FROM public.user_devices), (SELECT u1 FROM device_test_ids), 'identity is derived from auth');
SELECT is((SELECT first_seen_at FROM public.user_devices), now(), 'first seen uses server clock');
SELECT throws_ok($$UPDATE public.user_devices SET last_seen_at = now()$$, '42501', 'permission denied for table user_devices', 'direct timestamp changes are refused');
SELECT throws_ok($$INSERT INTO public.user_devices(user_id, device_id, browser_name, os_name, device_type) SELECT u2, device, 'Safari', 'iOS', 'phone' FROM device_test_ids$$, '42501', 'permission denied for table user_devices', 'direct cross-user inserts are refused');
RESET ROLE;
UPDATE public.user_devices SET last_seen_at = now() - interval '30 minutes' WHERE user_id = (SELECT u1 FROM device_test_ids);
SET LOCAL ROLE authenticated;
SELECT public.record_user_device(device, 'Safari', '18.0', 'iOS', 'phone') FROM device_test_ids;
SELECT is((SELECT last_seen_at FROM public.user_devices), now() - interval '30 minutes', 'repeat observations within an hour do not write');
RESET ROLE;
UPDATE public.user_devices SET last_seen_at = now() - interval '2 hours' WHERE user_id = (SELECT u1 FROM device_test_ids);
SET LOCAL ROLE authenticated;
SELECT public.record_user_device(device, 'Safari', '18.0', 'iOS', 'phone') FROM device_test_ids;
SELECT is((SELECT last_seen_at FROM public.user_devices), now(), 'return after an hour advances last seen');
SELECT public.record_user_device(device, 'Safari', '18.1', 'iOS', 'phone') FROM device_test_ids;
SELECT is((SELECT browser_version FROM public.user_devices), '18.1', 'browser upgrade updates the existing installation');
SELECT is((SELECT first_seen_at FROM public.user_devices), now(), 'first seen survives updates');
SELECT public.record_user_device(gen_random_uuid(), 'Firefox', NULL, 'Unknown', 'unknown');
SELECT is((SELECT count(*) FROM public.user_devices), 2::bigint, 'second installation has a separate row');
SELECT set_config('request.jwt.claim.sub', (SELECT u2::text FROM device_test_ids), true);
SELECT is((SELECT count(*) FROM public.user_devices), 0::bigint, 'another user cannot read the first user devices');
SELECT public.record_user_device(device, 'Chrome', '143', 'Windows', 'desktop') FROM device_test_ids;
SELECT is((SELECT count(*) FROM public.user_devices), 1::bigint, 'shared browser cookie remains account scoped');
SELECT throws_ok($$SELECT public.record_user_device(gen_random_uuid(), 'Chrome', NULL, 'Windows', 'invalid')$$, '23514', NULL, 'invalid device types are rejected');
SELECT throws_ok($$SELECT public.record_user_device(gen_random_uuid(), repeat('x', 65), NULL, 'Windows', 'desktop')$$, '23514', NULL, 'oversized metadata is rejected');
SELECT set_config('request.jwt.claim.sub', '', true);
SELECT throws_ok($$SELECT public.record_user_device(gen_random_uuid(), 'Chrome', NULL, 'Windows', 'desktop')$$, '42501', 'Authentication required', 'no verified identity cannot record');
SET LOCAL ROLE anon;
SELECT throws_ok($$SELECT * FROM public.user_devices$$, '42501', 'permission denied for table user_devices', 'anonymous table reads are denied');
SELECT throws_ok($$SELECT public.record_user_device(gen_random_uuid(), 'Chrome', NULL, 'Windows', 'desktop')$$, '42501', 'permission denied for function record_user_device', 'anonymous RPC access is denied');
SET LOCAL ROLE service_role;
SELECT is((SELECT count(*) FROM public.user_devices WHERE user_id IN (SELECT u1 FROM device_test_ids UNION ALL SELECT u2 FROM device_test_ids)), 3::bigint, 'admin service role can read both users');
RESET ROLE;
DELETE FROM auth.users WHERE id = (SELECT u1 FROM device_test_ids);
SELECT is((SELECT count(*) FROM public.user_devices WHERE user_id IN (SELECT u1 FROM device_test_ids UNION ALL SELECT u2 FROM device_test_ids)), 1::bigint, 'account deletion cascades only its own device records');
-- An authenticated caller cannot grow its account history without bound.
SELECT set_config('request.jwt.claim.sub', (SELECT u2::text FROM device_test_ids), true);
SET LOCAL ROLE authenticated;
SELECT public.record_user_device(gen_random_uuid(), 'Chrome', NULL, 'Windows', 'desktop') FROM generate_series(1, 40);
SELECT is((SELECT count(*) FROM public.user_devices), 32::bigint, 'fresh identifiers are capped at 32 installations');
RESET ROLE;
UPDATE public.user_devices SET last_seen_at = now() - interval '2 hours' WHERE user_id = (SELECT u2 FROM device_test_ids);
UPDATE public.user_devices SET last_seen_at = now() - interval '1 day'
WHERE user_id = (SELECT u2 FROM device_test_ids) AND device_id = (SELECT min(device_id::text)::uuid FROM public.user_devices WHERE user_id = (SELECT u2 FROM device_test_ids));
CREATE TEMP TABLE evicted_device AS SELECT device_id FROM public.user_devices WHERE user_id = (SELECT u2 FROM device_test_ids) ORDER BY last_seen_at LIMIT 1;
GRANT SELECT ON evicted_device TO authenticated;
UPDATE device_test_ids SET device = gen_random_uuid();
SET LOCAL ROLE authenticated;
SELECT public.record_user_device(device, 'Chrome', NULL, 'Windows', 'desktop') FROM device_test_ids;
SELECT is((SELECT count(*) FROM public.user_devices), 32::bigint, 'admitting another installation keeps the cap');
SELECT is((SELECT count(*) FROM public.user_devices WHERE device_id = (SELECT device_id FROM evicted_device)), 0::bigint, 'oldest installation is evicted first');
SELECT public.record_user_device(device, 'Chrome', '144', 'Windows', 'desktop') FROM device_test_ids;
SELECT is((SELECT count(*) FROM public.user_devices), 32::bigint, 'an existing installation updates without extra admissions');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
