#!/usr/bin/env bash
# deploy/app/release.sh — Promote a staged release to live.
#
# Runs ON THE SERVER. CI has already rsynced build/ and package files into
# ${MANKUNKU_ROOT}/releases/<id>/. This script finishes the deploy: installs
# production dependencies, atomically swaps the `current` symlink, restarts
# PM2, and prunes old releases.
#
# Usage:
#   bash release.sh <release-id>
#
# Environment:
#   MANKUNKU_ROOT   App root (default: /home/deploy/mankunku). Override for tests.
#   KEEP_RELEASES   How many past releases to retain (default: 5).

set -euo pipefail

RELEASE_ID="${1:-}"
ROOT="${MANKUNKU_ROOT:-/home/deploy/mankunku}"

if [[ -z "$RELEASE_ID" ]]; then
    echo "error: missing release id" >&2
    echo "usage: $0 <release-id>" >&2
    exit 2
fi

# RELEASE_ID becomes part of filesystem paths and the `current` symlink target,
# so reject anything that isn't the CI-generated format (YYYYMMDD-HHMMSS-<7-hex>).
# This forecloses path-traversal (../) and other shell-metacharacter surprises.
if [[ ! "$RELEASE_ID" =~ ^[0-9]{8}-[0-9]{6}-[0-9a-f]{7}$ ]]; then
    echo "error: invalid release id: $(printf '%q' "$RELEASE_ID")" >&2
    echo "expected format: YYYYMMDD-HHMMSS-<7-hex>" >&2
    exit 2
fi

STAGE="${ROOT}/releases/${RELEASE_ID}"
if [[ ! -d "$STAGE" ]]; then
    echo "error: staged release not found: $STAGE" >&2
    exit 2
fi

echo "==> Installing production dependencies in staged release"
(
    cd "$STAGE"
    npm ci --omit=dev
)

# Atomic symlink swap: write a temporary symlink, then rename it over `current`.
# `mv -f` uses rename(2), which is atomic on POSIX filesystems. When the
# destination is itself a symlink (not a directory), rename(2) replaces the
# symlink in one step without following it — so no -T flag needed (GNU-only).
echo "==> Swapping current -> releases/${RELEASE_ID}"
TMP_LINK="${ROOT}/current.tmp.$$"
# Clean up the temp symlink if anything below fails before the mv completes.
trap 'rm -f "$TMP_LINK"' EXIT
ln -sfn "releases/${RELEASE_ID}" "$TMP_LINK"
# If `current` exists as a real directory (not a symlink), `mv -f` would move
# TMP_LINK *into* it rather than replacing it. Abort instead.
if [[ -e "${ROOT}/current" && ! -L "${ROOT}/current" ]]; then
    echo "error: ${ROOT}/current exists and is not a symlink; refusing to swap" >&2
    exit 1
fi
mv -f "$TMP_LINK" "${ROOT}/current"
trap - EXIT

echo "==> Restarting PM2 against new release"
# PM2 resolves a relative `script:` in the ecosystem config against its own
# PWD (not against the config's `cwd:` field — that only sets the *runtime*
# cwd of the spawned process). The deploy user's login shell starts in
# ~/mankunku, so without this cd PM2 would look for ./build/index.js at
# ~/mankunku/build/index.js and fail with "Script not found".
(
    cd "${ROOT}/current"
    pm2 startOrRestart ecosystem.config.cjs --env production
    pm2 save
)

echo "==> Pruning old releases (keep last ${KEEP_RELEASES:-5})"
KEEP="${KEEP_RELEASES:-5}"
# `ls -1t` lists by mtime, newest first. Portable across macOS and Linux
# (unlike `find -printf`, which is GNU-only and matters for the local test
# harness). `tail -n +N` skips the first KEEP entries; the rest are pruned.
cd "${ROOT}/releases"
# shellcheck disable=SC2012
ls -1t | tail -n +$((KEEP + 1)) | while read -r dir; do
    [[ -n "$dir" ]] || continue
    # Release IDs are generated by CI as YYYYMMDD-HHMMSS-<7-hex>. Anything else
    # is human-created (or worse) and must not be passed to `rm -rf`.
    if [[ ! "$dir" =~ ^[0-9]{8}-[0-9]{6}-[0-9a-f]{7}$ ]]; then
        echo "    skipping non-matching release-id: $(printf '%q' "$dir")" >&2
        continue
    fi
    echo "    pruning releases/${dir}"
    rm -rf -- "$dir"
done

echo "==> Done. Live release: $(readlink "${ROOT}/current")"
