/**
 * PDF import vs MuseScore import — five real charts (re-recorded 2026-07-23
 * after the bar-wise schema rework; see git history for the fixture's
 * recording pipeline state).
 *
 * RUN VARIANCE, measured: the extraction has no temperature control on this
 * model, and identical inputs swing between near-perfect and shaky across
 * runs (ATTYA's form came back exactly right in one recording and merged in
 * the next; TWNBAY once silently dropped half its systems). The route now
 * retries structurally shaky attempts once, and printed system bar numbers
 * resync undercounts — but single-sample extraction remains probabilistic,
 * which is why review-in-editor stays mandatory.
 *
 * The MuseScore import of each song is the reference (fixtures generated by
 * running the .mscz sources through the app's import flow: tenor part
 * preference + the Bb source default for files claiming concert pitch; they
 * match the sheets in the user's dev environment). Each song's PDF — the
 * printed export of the same score — was run once through the live
 * /api/lead-sheet-parse route and the response recorded, so CI compares the
 * two pipelines deterministically. PDFs live in `Leadsheets/PDF/` for
 * re-recording.
 *
 * The PDF fixtures pass through the same written→concert transform the
 * import page applies for a tenor user (Bb source), because every one of
 * these charts is printed at written pitch.
 *
 * ── Fixed by the copyist-prompt rework (now strict passes) ──────────────
 *
 * KEY-BY-REPUTATION: the model used to return the tune's well-known key
 * instead of the printed signature on 3/5 charts. Keys now come from a
 * mechanical keySignature.fifths count — all five agree with the print.
 * Melody register followed the same fix (pitches now printed-faithful), and
 * TWNBAY's colored-highlight chart went from ZERO melody notes to a full
 * extraction. ATTYA's bar count corrected (41, incl. pickup + intro).
 *
 * ── Deterministic per-system pipeline (fixtures re-recorded 2026-07-24) ──
 *
 * Geometry (analyzePageGeometry) counts systems and bars exactly on all
 * five charts; the text layer supplies chords/marks/endings; the model only
 * transcribes melody per system. BAR COUNTS, KEYS, and METERS now pass
 * strictly on 5/5; FORM passes on 3/5 (Fly Me: a spurious model |: on the
 * B section; TWNBAY: section-label drift on its C section).
 *
 * Remaining defect classes:
 *
 * D3 CHORD BEAT INTERPOLATION: content and bar assignment are exact; two
 *    chords in a 4/4 bar resolve to beats 1 and 3 unless decisively later,
 *    but charts that anchor a second chord on beat 4 (Autumn bar 23, two
 *    Fly Me bars) sit under the decisive threshold. A Train, ATTYA pass
 *    strictly.
 *
 * D4 MELODY RHYTHM. The model's durations/offsets drift enough that exact
 *    note matches stay rare — the review-in-editor step remains mandatory.
 *
 * When an `it.fails` starts passing, vitest flags it — promote it to `it`.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { writtenSheetToConcert } from '$lib/tunes/source-transposition';
import { INSTRUMENTS } from '$lib/types/instruments';
import { fractionToFloat } from '$lib/music/intervals';
import type { Tune } from '$lib/types/tune';
import { existsSync } from 'node:fs';
import { CORPUS } from '../helpers/leadsheet-corpus';

// Charts whose PDF fixture has been recorded (new corpus entries join the
// suite as soon as their fixture lands — see the corpus manifest header).
const CHARTS = CORPUS.filter((c) =>
	existsSync(
		new URL(`../fixtures/leadsheets/pdf-vs-musescore/${c.slug}.pdf-import.json`, import.meta.url)
	)
);




const fixture = (name: string): string =>
	fileURLToPath(new URL(`../fixtures/leadsheets/pdf-vs-musescore/${name}`, import.meta.url));

function load(slug: string): { ref: Tune; pdf: Tune } {
	const ref = JSON.parse(readFileSync(fixture(`${slug}.musescore-import.json`), 'utf8')) as Tune;
	const res = JSON.parse(readFileSync(fixture(`${slug}.pdf-import.json`), 'utf8')) as {
		sheet: Tune;
	};
	// The import page's default for a tenor user: the chart is a Bb part.
	const pdf = writtenSheetToConcert(res.sheet, 'Bb', INSTRUMENTS['tenor-sax']);
	return { ref, pdf };
}

/** Absolute-timeline chord changes: [barOffsetFloat, root+quality]. */
function chords(sheet: Tune): Array<[number, string]> {
	const out: Array<[number, string]> = [];
	let base = 0;
	const barDur = sheet.timeSignature[0] / sheet.timeSignature[1];
	for (const sec of sheet.sections) {
		for (const h of sec.harmony) {
			out.push([
				(base + fractionToFloat(h.startOffset)) / barDur,
				`${h.chord.root}${h.chord.quality}`
			]);
		}
		base += sec.bars * barDur;
	}
	return out.sort((a, b) => a[0] - b[0]);
}

/** Position-free chord sequence, for content-only agreement. */
const chordSeq = (sheet: Tune): string[] => chords(sheet).map(([, c]) => c);

/** Absolute-timeline melody: [offsetFloat, pitch, durationFloat]. */
function melody(sheet: Tune): Array<[number, number, number]> {
	const out: Array<[number, number, number]> = [];
	let base = 0;
	const barDur = sheet.timeSignature[0] / sheet.timeSignature[1];
	for (const sec of sheet.sections) {
		for (const n of sec.notes) {
			if (n.pitch === null) continue;
			out.push([base + fractionToFloat(n.offset), n.pitch, fractionToFloat(n.duration)]);
		}
		base += sec.bars * barDur;
	}
	return out;
}

const totalBars = (sheet: Tune): number =>
	sheet.sections.reduce((sum, s) => sum + s.bars, 0);

/** Longest-common-subsequence length between two arrays under `eq`. */
function lcs<T>(a: T[], b: T[], eq: (x: T, y: T) => boolean): number {
	const dp: number[] = new Array(b.length + 1).fill(0);
	for (let i = 1; i <= a.length; i++) {
		let prev = 0;
		for (let j = 1; j <= b.length; j++) {
			const tmp = dp[j];
			dp[j] = eq(a[i - 1], b[j - 1]) ? prev + 1 : Math.max(dp[j], dp[j - 1]);
			prev = tmp;
		}
	}
	return dp[b.length];
}

/** Fraction of the reference recovered by the candidate (0..1). */
function agreement<T>(ref: T[], got: T[], eq: (x: T, y: T) => boolean): number {
	if (ref.length === 0) return got.length === 0 ? 1 : 0;
	return lcs(ref, got, eq) / ref.length;
}

const strictEq = <T>(x: T, y: T): boolean => JSON.stringify(x) === JSON.stringify(y);
const samePitch = (x: [number, number, number], y: [number, number, number]): boolean =>
	x[1] === y[1];

describe.each(CHARTS)('$slug — PDF import vs MuseScore import', ({ slug, knownDefects, floors }) => {
	const { ref, pdf } = load(slug);
	const defects = new Set(knownDefects);
	const target = (id: string) => (defects.has(id) ? it.fails : it);

	// ── Strict targets: what a faithful PDF import must satisfy ─────────
	it('agrees on the time signature', () => {
		expect(pdf.timeSignature).toEqual(ref.timeSignature);
	});

	target('key')('agrees on the concert key', () => {
		expect(pdf.key).toBe(ref.key);
	});

	target('bars')('agrees on the total bar count', () => {
		expect(totalBars(pdf)).toBe(totalBars(ref));
	});

	target('form')('agrees on the form (sections, repeats, endings)', () => {
		const form = (s: Tune) =>
			s.sections.map((sec) => [
				sec.bars,
				sec.repeatStart ?? false,
				sec.repeatEnd ?? false,
				sec.ending ?? 0
			]);
		expect(form(pdf)).toEqual(form(ref));
	});

	target('chords')('recovers every chord change at its printed position', () => {
		expect(chords(pdf)).toEqual(chords(ref));
	});

	target('melody')('recovers the full melody note-for-note', () => {
		expect(agreement(melody(ref), melody(pdf), strictEq)).toBe(1);
	});

	target('pitches')('recovers the melody pitch sequence', () => {
		expect(agreement(melody(ref), melody(pdf), samePitch)).toBe(1);
	});

	target('any-melody')('extracts a non-trivial melody (at least half the notes)', () => {
		expect(melody(pdf).length).toBeGreaterThanOrEqual(melody(ref).length / 2);
	});

	// ── Regression floors: the recorded run's quality must not sink ─────
	it('chord-sequence agreement stays at or above the recorded floor', () => {
		expect(agreement(chordSeq(ref), chordSeq(pdf), (a, b) => a === b)).toBeGreaterThanOrEqual(
			floors.chordSeq
		);
	});

	it('melody pitch agreement stays at or above the recorded floor', () => {
		expect(agreement(melody(ref), melody(pdf), samePitch)).toBeGreaterThanOrEqual(
			floors.pitchSeq
		);
	});
});
