/**
 * PDF import vs MuseScore import — five real charts (recorded 2026-07-23).
 *
 * The MuseScore import of each song is the reference (fixtures generated by
 * running the .mscz sources through the app's import flow: tenor part
 * preference + the Bb source default for files claiming concert pitch; they
 * match the sheets in the user's dev environment). Each song's PDF — the
 * printed export of the same score — was run once through the live
 * /api/lead-sheet-parse route and the response recorded, so CI compares the
 * two pipelines deterministically. PDFs live in `leadsheet PDFs/` for
 * re-recording.
 *
 * The PDF fixtures pass through the same written→concert transform the
 * import page applies for a tenor user (Bb source), because every one of
 * these charts is printed at written pitch.
 *
 * ── Current defect classes (each pinned by an `it.fails` below) ─────────
 *
 * D1 KEY-BY-REPUTATION. On 3 of 5 charts the extraction returned the tune's
 *    WELL-KNOWN key instead of the printed key signature (ATTYA: Ab for a
 *    chart printed in Bb; Autumn Leaves: G for a chart printed in A; Fly Me:
 *    C for a chart printed in D) — while the CHORD SYMBOLS faithfully follow
 *    the print. The two fields disagree inside one extraction, so no single
 *    source-transposition setting can land both: the page's Bb shift puts
 *    the chords right and those keys wrong.
 *
 * D2 FORM INVENTION. Repeats get written out (A Train: 32 linear bars for a
 *    25-bar chart with 1st/2nd endings), volta sections merge into their
 *    body (Autumn: 9-bar "A" swallowing the first ending), pickup/intro
 *    bars are dropped or reshaped (TWNBAY loses its pickup bar; ATTYA's
 *    pickup + 4-bar repeated intro becomes a 2-bar "Intro"), and Real-Book
 *    segmentation is imposed over the engraved layout (ATTYA: 8/8/8/12).
 *    Bar counts can be plainly wrong (Fly Me: 13+13 for a 16+16 chart).
 *
 * D3 CHORD POSITIONS INHERIT D2. Chord content is the bright spot —
 *    sequence agreement 90-100% across all five — but absolute positions
 *    shift wherever the form does, so position-strict comparison fails.
 *
 * D4 MELODY UNRELIABLE. Register is normalized inconsistently (best-fit
 *    transposition varies per chart between -12 and -14 relative to the
 *    print), recall is partial (61-85 notes of 67-112), rhythm drifts, and
 *    on TWNBAY (a chart with colored analysis highlights) the extraction
 *    returned ZERO melody notes.
 *
 * When an `it.fails` starts passing, vitest flags it — promote it to `it`.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { writtenSheetToConcert } from '$lib/leadsheets/source-transposition';
import { INSTRUMENTS } from '$lib/types/instruments';
import { fractionToFloat } from '$lib/music/intervals';
import type { LeadSheet } from '$lib/types/lead-sheet';

const SONGS = [
	'all-the-things-you-are',
	'autumn-leaves',
	'fly-me-to-the-moon',
	'take-the-a-train',
	'there-will-never-be-another-you'
] as const;
type Slug = (typeof SONGS)[number];

/** Which strict expectations each song currently fails (see header). */
const KNOWN_DEFECTS: Record<Slug, Set<string>> = {
	'all-the-things-you-are': new Set(['key', 'bars', 'form', 'chords', 'melody', 'pitches']),
	'autumn-leaves': new Set(['key', 'form', 'chords', 'melody', 'pitches']),
	'fly-me-to-the-moon': new Set(['key', 'bars', 'form', 'chords', 'melody', 'pitches']),
	'take-the-a-train': new Set(['bars', 'form', 'chords', 'melody', 'pitches']),
	'there-will-never-be-another-you': new Set(['bars', 'form', 'chords', 'melody', 'pitches', 'any-melody'])
};

/** Regression floors pinned just under the recorded run's quality. */
const FLOORS: Record<Slug, { chordSeq: number; pitchSeq: number }> = {
	'all-the-things-you-are': { chordSeq: 0.95, pitchSeq: 0.2 },
	'autumn-leaves': { chordSeq: 0.95, pitchSeq: 0.25 },
	'fly-me-to-the-moon': { chordSeq: 0.9, pitchSeq: 0.35 },
	'take-the-a-train': { chordSeq: 0.85, pitchSeq: 0.45 },
	'there-will-never-be-another-you': { chordSeq: 0.95, pitchSeq: 0 }
};

const fixture = (name: string): string =>
	fileURLToPath(new URL(`../fixtures/leadsheets/pdf-vs-musescore/${name}`, import.meta.url));

function load(slug: Slug): { ref: LeadSheet; pdf: LeadSheet } {
	const ref = JSON.parse(readFileSync(fixture(`${slug}.musescore-import.json`), 'utf8')) as LeadSheet;
	const res = JSON.parse(readFileSync(fixture(`${slug}.pdf-import.json`), 'utf8')) as {
		sheet: LeadSheet;
	};
	// The import page's default for a tenor user: the chart is a Bb part.
	const pdf = writtenSheetToConcert(res.sheet, 'Bb', INSTRUMENTS['tenor-sax']);
	return { ref, pdf };
}

/** Absolute-timeline chord changes: [barOffsetFloat, root+quality]. */
function chords(sheet: LeadSheet): Array<[number, string]> {
	const out: Array<[number, string]> = [];
	let base = 0;
	const barDur = sheet.timeSignature[0] / sheet.timeSignature[1];
	for (const sec of sheet.sections) {
		for (const h of sec.harmony) {
			out.push([
				(base + fractionToFloat(h.startOffset)) / barDur,
				`${h.chord.root}${h.chord.quality}`
			]);
		}
		base += sec.bars * barDur;
	}
	return out.sort((a, b) => a[0] - b[0]);
}

/** Position-free chord sequence, for content-only agreement. */
const chordSeq = (sheet: LeadSheet): string[] => chords(sheet).map(([, c]) => c);

/** Absolute-timeline melody: [offsetFloat, pitch, durationFloat]. */
function melody(sheet: LeadSheet): Array<[number, number, number]> {
	const out: Array<[number, number, number]> = [];
	let base = 0;
	const barDur = sheet.timeSignature[0] / sheet.timeSignature[1];
	for (const sec of sheet.sections) {
		for (const n of sec.notes) {
			if (n.pitch === null) continue;
			out.push([base + fractionToFloat(n.offset), n.pitch, fractionToFloat(n.duration)]);
		}
		base += sec.bars * barDur;
	}
	return out;
}

const totalBars = (sheet: LeadSheet): number =>
	sheet.sections.reduce((sum, s) => sum + s.bars, 0);

/** Longest-common-subsequence length between two arrays under `eq`. */
function lcs<T>(a: T[], b: T[], eq: (x: T, y: T) => boolean): number {
	const dp: number[] = new Array(b.length + 1).fill(0);
	for (let i = 1; i <= a.length; i++) {
		let prev = 0;
		for (let j = 1; j <= b.length; j++) {
			const tmp = dp[j];
			dp[j] = eq(a[i - 1], b[j - 1]) ? prev + 1 : Math.max(dp[j], dp[j - 1]);
			prev = tmp;
		}
	}
	return dp[b.length];
}

/** Fraction of the reference recovered by the candidate (0..1). */
function agreement<T>(ref: T[], got: T[], eq: (x: T, y: T) => boolean): number {
	if (ref.length === 0) return got.length === 0 ? 1 : 0;
	return lcs(ref, got, eq) / ref.length;
}

const strictEq = <T>(x: T, y: T): boolean => JSON.stringify(x) === JSON.stringify(y);
const samePitch = (x: [number, number, number], y: [number, number, number]): boolean =>
	x[1] === y[1];

describe.each(SONGS)('%s — PDF import vs MuseScore import', (slug) => {
	const { ref, pdf } = load(slug);
	const target = (id: string) => (KNOWN_DEFECTS[slug].has(id) ? it.fails : it);

	// ── Strict targets: what a faithful PDF import must satisfy ─────────
	it('agrees on the time signature', () => {
		expect(pdf.timeSignature).toEqual(ref.timeSignature);
	});

	target('key')('agrees on the concert key', () => {
		expect(pdf.key).toBe(ref.key);
	});

	target('bars')('agrees on the total bar count', () => {
		expect(totalBars(pdf)).toBe(totalBars(ref));
	});

	target('form')('agrees on the form (sections, repeats, endings)', () => {
		const form = (s: LeadSheet) =>
			s.sections.map((sec) => [
				sec.bars,
				sec.repeatStart ?? false,
				sec.repeatEnd ?? false,
				sec.ending ?? 0
			]);
		expect(form(pdf)).toEqual(form(ref));
	});

	target('chords')('recovers every chord change at its printed position', () => {
		expect(chords(pdf)).toEqual(chords(ref));
	});

	target('melody')('recovers the full melody note-for-note', () => {
		expect(agreement(melody(ref), melody(pdf), strictEq)).toBe(1);
	});

	target('pitches')('recovers the melody pitch sequence', () => {
		expect(agreement(melody(ref), melody(pdf), samePitch)).toBe(1);
	});

	target('any-melody')('extracts a non-trivial melody (at least half the notes)', () => {
		expect(melody(pdf).length).toBeGreaterThanOrEqual(melody(ref).length / 2);
	});

	// ── Regression floors: the recorded run's quality must not sink ─────
	it('chord-sequence agreement stays at or above the recorded floor', () => {
		expect(agreement(chordSeq(ref), chordSeq(pdf), (a, b) => a === b)).toBeGreaterThanOrEqual(
			FLOORS[slug].chordSeq
		);
	});

	it('melody pitch agreement stays at or above the recorded floor', () => {
		expect(
			agreement(melody(ref), melody(pdf), samePitch)
		).toBeGreaterThanOrEqual(FLOORS[slug].pitchSeq);
	});
});
